import { NextRequest, NextResponse } from "next/server";
import { renderToBuffer } from "@react-pdf/renderer";
import React from "react";
import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer";
import type { WizardSession, GenerateResponse } from "@/lib/types";

// Register a clean font
Font.register({
  family: "Inter",
  fonts: [
    { src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiJ-Ek-_EeA.woff", fontWeight: 400 },
    { src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYAZ9hiJ-Ek-_EeA.woff", fontWeight: 700 },
  ],
});

const styles = StyleSheet.create({
  page: { fontFamily: "Inter", fontSize: 10, padding: 48, color: "#111827", lineHeight: 1.6 },
  header: { marginBottom: 32, borderBottom: "2px solid #6366f1", paddingBottom: 16 },
  titleRow: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 8 },
  logoBox: { width: 36, height: 36, backgroundColor: "#6366f1", borderRadius: 8 },
  title: { fontSize: 22, fontWeight: 700, color: "#1e1b4b" },
  subtitle: { fontSize: 11, color: "#6b7280" },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 13, fontWeight: 700, color: "#4338ca", marginBottom: 8, textTransform: "uppercase", letterSpacing: 0.5 },
  label: { fontWeight: 700, color: "#374151", marginBottom: 2 },
  value: { color: "#4b5563", marginBottom: 6 },
  colorRow: { flexDirection: "row", gap: 8, marginTop: 4, marginBottom: 8 },
  colorSwatch: { width: 24, height: 24, borderRadius: 4 },
  promptBox: { backgroundColor: "#f8fafc", padding: 12, borderRadius: 6, border: "1px solid #e2e8f0", marginBottom: 10 },
  promptLabel: { fontWeight: 700, fontSize: 9, color: "#6366f1", marginBottom: 4, textTransform: "uppercase" },
  promptText: { fontSize: 9, color: "#374151", lineHeight: 1.7 },
  ctaBox: { backgroundColor: "#1e1b4b", padding: 16, borderRadius: 8, marginTop: 24 },
  ctaTitle: { fontSize: 14, fontWeight: 700, color: "#fff", marginBottom: 8 },
  ctaRow: { flexDirection: "row", gap: 12 },
  ctaTier: { flex: 1, backgroundColor: "#312e81", padding: 10, borderRadius: 6 },
  ctaPrice: { fontSize: 14, fontWeight: 700, color: "#a5b4fc" },
  ctaTierName: { fontSize: 10, fontWeight: 700, color: "#fff", marginBottom: 2 },
  ctaDesc: { fontSize: 8, color: "#c7d2fe" },
  footer: { position: "absolute", bottom: 24, left: 48, right: 48, flexDirection: "row", justifyContent: "space-between", fontSize: 8, color: "#9ca3af" },
});

function DesignBriefPDF({ session, generated }: { session: WizardSession; generated: GenerateResponse }) {
  const { brand, inspirationSites, distillation, siteAnalyses } = session;

  return React.createElement(
    Document,
    { title: `SitePrompt Design Brief — ${brand.name}` },
    React.createElement(
      Page,
      { size: "A4", style: styles.page },
      // Header
      React.createElement(View, { style: styles.header },
        React.createElement(View, { style: styles.titleRow },
          React.createElement(View, { style: styles.logoBox }),
          React.createElement(View, null,
            React.createElement(Text, { style: styles.title }, `${brand.name} — Design Brief`),
            React.createElement(Text, { style: styles.subtitle }, `Generated by SitePrompt · ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`),
          )
        )
      ),

      // Brand Section
      React.createElement(View, { style: styles.section },
        React.createElement(Text, { style: styles.sectionTitle }, "Your Brand"),
        React.createElement(Text, { style: styles.label }, "Purpose"),
        React.createElement(Text, { style: styles.value }, brand.purpose),
        React.createElement(Text, { style: styles.label }, "Claim to Fame"),
        React.createElement(Text, { style: styles.value }, brand.claimToFame),
        brand.currentSiteUrl ? React.createElement(View, null,
          React.createElement(Text, { style: styles.label }, "Current Site"),
          React.createElement(Text, { style: styles.value }, brand.currentSiteUrl)
        ) : null,
        React.createElement(Text, { style: styles.label }, "Brand Colors"),
        React.createElement(View, { style: styles.colorRow },
          ...brand.colors.map((c, i) =>
            React.createElement(View, { key: i, style: { ...styles.colorSwatch, backgroundColor: c } })
          )
        ),
        React.createElement(Text, { style: { ...styles.value, fontSize: 8, color: "#9ca3af" } }, brand.colors.join("  ·  ")),
      ),

      // Aesthetic Prefs
      React.createElement(View, { style: styles.section },
        React.createElement(Text, { style: styles.sectionTitle }, "Aesthetic Preferences"),
        React.createElement(Text, { style: styles.label }, "Overall Aesthetic"),
        React.createElement(Text, { style: styles.value }, distillation.overallAesthetic || "—"),
        React.createElement(Text, { style: styles.label }, "Primary Audience"),
        React.createElement(Text, { style: styles.value }, distillation.primaryAudience || "—"),
        React.createElement(Text, { style: styles.label }, "Emotion to Convey"),
        React.createElement(Text, { style: styles.value }, distillation.emotionToConvey || "—"),
        React.createElement(Text, { style: styles.label }, "What to Avoid"),
        React.createElement(Text, { style: styles.value }, distillation.whatToAvoid || "—"),
      ),

      // Inspiration Sites
      React.createElement(View, { style: styles.section },
        React.createElement(Text, { style: styles.sectionTitle }, "Design Inspiration"),
        ...inspirationSites.map((site, i) => {
          const analysis = siteAnalyses[i];
          return React.createElement(View, { key: i, style: { marginBottom: 12 } },
            React.createElement(Text, { style: { fontWeight: 700, color: "#374151", marginBottom: 2 } }, `${i + 1}. ${site.name} — ${site.url}`),
            React.createElement(Text, { style: styles.value }, site.whyYouLikeIt),
            analysis ? React.createElement(View, null,
              React.createElement(Text, { style: { fontSize: 9, color: "#6b7280" } },
                `Typography: ${[analysis.typography.serif && "Serif", analysis.typography.sansSerif && "Sans-serif", analysis.typography.display && "Display", analysis.typography.monospace && "Monospace"].filter(Boolean).join(", ") || "—"}${analysis.typography.notes ? ` — ${analysis.typography.notes}` : ""}`
              ),
              React.createElement(Text, { style: { fontSize: 9, color: "#6b7280" } },
                `Colors: ${[analysis.colors.light && "Light", analysis.colors.dark && "Dark", analysis.colors.vibrant && "Vibrant", analysis.colors.muted && "Muted"].filter(Boolean).join(", ") || "—"}${analysis.colors.notes ? ` — ${analysis.colors.notes}` : ""}`
              ),
              analysis.specificElements ? React.createElement(Text, { style: { fontSize: 9, color: "#6b7280" } },
                `Specific elements: ${analysis.specificElements}`
              ) : null,
            ) : null,
          );
        })
      ),

      // Design Synthesis
      React.createElement(View, { style: styles.section },
        React.createElement(Text, { style: styles.sectionTitle }, "Design Synthesis"),
        React.createElement(Text, { style: styles.value }, generated.summary),
      ),

      // Claude Design Prompts
      React.createElement(View, { style: styles.section },
        React.createElement(Text, { style: styles.sectionTitle }, "Claude Design Prompts"),
        React.createElement(View, { style: styles.promptBox },
          React.createElement(Text, { style: styles.promptLabel }, "Quick Prototype Prompt"),
          React.createElement(Text, { style: styles.promptText }, generated.quickPrompt),
        ),
        React.createElement(View, { style: styles.promptBox },
          React.createElement(Text, { style: styles.promptLabel }, "Full Design System Prompt"),
          React.createElement(Text, { style: styles.promptText }, generated.fullPrompt),
        ),
        React.createElement(View, { style: styles.promptBox },
          React.createElement(Text, { style: styles.promptLabel }, "Complete Specification Prompt"),
          React.createElement(Text, { style: styles.promptText }, generated.specPrompt),
        ),
      ),

      // CTA
      React.createElement(View, { style: styles.ctaBox },
        React.createElement(Text, { style: styles.ctaTitle }, "Ready to build? ServiceVision turns your brief into a real product."),
        React.createElement(View, { style: styles.ctaRow },
          ...[
            { tier: "Starter", price: "$999", desc: "Landing page prototype" },
            { tier: "Growth", price: "$4,999", desc: "Full site / app prototype" },
            { tier: "Enterprise", price: "$19,999", desc: "Full-stack MVP" },
          ].map((t) =>
            React.createElement(View, { key: t.tier, style: styles.ctaTier },
              React.createElement(Text, { style: styles.ctaPrice }, t.price),
              React.createElement(Text, { style: styles.ctaTierName }, t.tier),
              React.createElement(Text, { style: styles.ctaDesc }, t.desc),
            )
          )
        ),
        React.createElement(Text, { style: { color: "#c7d2fe", fontSize: 9, marginTop: 10 } },
          "Schedule a free consult: https://calendly.com/servicevision/siteprompt"
        ),
      ),

      // Footer
      React.createElement(View, { style: styles.footer },
        React.createElement(Text, null, `SitePrompt · siteprompt.servicevision.io`),
        React.createElement(Text, null, `© ${new Date().getFullYear()} ServiceVision`),
      ),
    )
  );
}

export async function POST(req: NextRequest) {
  try {
    const { session, generated } = await req.json() as { session: WizardSession; generated: GenerateResponse };
    const element = React.createElement(DesignBriefPDF, { session, generated });
    // @ts-expect-error — renderToBuffer expects DocumentProps but our component returns a Document
    const buffer = await renderToBuffer(element);
    return new NextResponse(Buffer.from(buffer) as unknown as BodyInit, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="siteprompt-brief-${session.brand.name.toLowerCase().replace(/\s+/g, "-")}.pdf"`,
      },
    });
  } catch (err) {
    console.error("PDF error:", err);
    return NextResponse.json({ error: "PDF generation failed" }, { status: 500 });
  }
}
